# Generated by Django 3.1.2 on 2020-10-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Data da Criação')),
                ('created_hours', models.TimeField(auto_now=True, verbose_name='Horario de criação')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='Data de modificação')),
                ('modified_hours', models.TimeField(auto_now_add=True, verbose_name='Horario de modificação')),
                ('active', models.BooleanField(default=True, verbose_name='Ativado ?')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('baseregister_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CBV_search.baseregister')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('birth_time', models.TimeField(verbose_name='Horario de nascimento')),
                ('date_birth', models.DateField(verbose_name='Data de nascimento')),
            ],
            bases=('CBV_search.baseregister',),
        ),
    ]
