# Generated by Django 3.1.2 on 2020-10-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('baseregister_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CBV_search.baseregister')),
                ('name_category', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
            ],
            bases=('CBV_search.baseregister',),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='CBV_search.Category'),
        ),
    ]
