# Generated by Django 3.1.2 on 2020-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_search', '0002_auto_20201008_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='categoria',
            field=models.ManyToManyField(to='CBV_search.Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
    ]
