# Generated by Django 3.1.2 on 2020-10-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_search', '0003_auto_20201008_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='date_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='categoria',
            new_name='categories',
        ),
    ]
